version: "3.3"

services:
  vag-rad-db:
    image: postgis/postgis:16-master
    container_name: vag-bike-db
    shm_size: 2gb
    volumes:
      - ./dump:/dumpfiles
      - vag_bike_db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  vag_bike_db:
    external: true
