version: '3.4'

services:
  bikesharing:
    image: vag-rad-scraper
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${scraping_data_location}:/app/scraping_data
      - ${log_location}:/app/logs
    env_file:
      - .env
